'use client';
import {useMemo,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,Legend,BarChart,Bar} from 'recharts';
import {State,today,dayLabel,total} from '@/lib/money';
import {insights,Period} from '@/lib/insights';
export function FinancialInsights({state:s}:{state:State}){
 const [period,setPeriod]=useState<Period>('MTD');
 const now=today(),data=useMemo(()=>insights(s,period,now),[s,period,now]);
 const money=(n:number)=>new Intl.NumberFormat('en',{style:'currency',currency:s.currency,maximumFractionDigits:0}).format(n);
 const compact=(n:number)=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
 const sums=data.flow.reduce((a,b)=>({income:a.income+b.income,spending:a.spending+b.spending,debt:a.debt+b.debt}),{income:0,spending:0,debt:0});
 const last=data.points.at(-1);
 return <section className="panel financial-insights"><div className="section-title"><div><p className="eyebrow">YOUR MONEY, IN PERSPECTIVE</p><h2>See where your routine leads</h2><p className="fine">Recorded progress and a clear view ahead.</p></div><div className="period-controls" aria-label="Reporting period">{(['WTD','MTD','YTD'] as Period[]).map(p=><button key={p} aria-pressed={p===period} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div>
 <p className="fine">{period==='WTD'?'Week':period==='MTD'?'Month':'Year'} to date: {dayLabel(data.start)}–{dayLabel(now)}. Weeks begin Monday.</p>
 <div className="insight-charts"><article><h3>Recorded balance trend</h3><p className="fine">Cash + savings from saved payday reviews and your current balance record.</p>{data.history.length>1?<div className="insight-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.history}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={dayLabel} minTickGap={36}/><YAxis tickFormatter={compact} width={52}/><Tooltip formatter={(v)=>money(Number(v))} labelFormatter={v=>dayLabel(String(v))}/><Line dataKey="balance" name="Recorded balance" stroke="#176e61" strokeWidth={3} dot/></LineChart></ResponsiveContainer></div>:<div className="insight-empty">{data.history.length?`Recorded balance: ${money(data.history[0].balance)}. `:''}Save payday reviews on at least two dates in this period to see your trend.</div>}</article>
 <article><h3>Projected balance</h3><p className="fine">From {dayLabel(s.asOf)} to {dayLabel(data.end)}. Spending accounts and savings shown separately.</p>{data.available?<div className="insight-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.points}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={dayLabel} minTickGap={36}/><YAxis tickFormatter={compact} width={52}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>dayLabel(String(v))}/><Legend/><Line dataKey="cash" name="Cash" stroke="#176e61" strokeWidth={2} dot={false}/><Line dataKey="savings" name="Savings" stroke="#a27638" strokeWidth={2} strokeDasharray="5 4" dot={false}/></LineChart></ResponsiveContainer></div>:<div className="insight-empty">Update your balances in Payday to project this period. Forecasts support up to 366 days from your balance date.</div>}</article></div>
 {data.stale&&<p className="insight-notice">Your balances are dated {dayLabel(s.asOf)}. Scheduled activity since then is estimated, not confirmed. Update them in Payday for a fresh forecast.</p>}
 {data.available&&<><div className="insight-totals"><div><span>Expected income</span><strong>{money(sums.income)}</strong></div><div><span>Scheduled spending</span><strong>{money(sums.spending)}</strong></div><div><span>Debt payments</span><strong>{money(sums.debt)}</strong></div><div><span>Period-end cash + savings</span><strong>{money((last?.cash??0)+(last?.savings??0))}</strong></div></div><h3>Scheduled cash flow</h3><p className="fine">After your balance date through {dayLabel(data.end)} across all accounts. Internal transfers are excluded. These are projections; Bloom does not record actual income or spending history.</p>{data.flow.length>0?<div className="insight-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.flow}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={dayLabel} minTickGap={36}/><YAxis tickFormatter={compact} width={52}/><Tooltip formatter={v=>money(Number(v))}/><Legend/><Bar dataKey="income" name="Income" fill="#176e61" radius={[4,4,0,0]}/><Bar dataKey="spending" name="Spending" fill="#bc8a68" radius={[4,4,0,0]}/><Bar dataKey="debt" name="Debt payments" fill="#7b7798" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>:<p className="insight-empty">No scheduled cash flow in this forecast. Add expected income and expenses in Cash flow.</p>}</>}
 <details><summary>What is included?</summary><p className="fine">Expected income uses your entered amount and dates, including bonuses, sales, pensions and investment payouts. Unconfirmed items marked excluded do not count. Investment and retirement balances ({money(total(s,'investment')+total(s,'retirement'))}) are separate from cash and savings; no market growth is assumed. Transfers to these accounts reduce available cash but are not expenses. Credit limits are not assets. Debt payments use fixed entered minimums and approximate monthly interest; fees, new card purchases and grace periods are not modeled. Extra-payment scenarios in Loans are separate.</p></details>
 </section>;
}
