'use client';
import { MoneyInput } from '@/components/money-input';
import {useMemo,useState} from 'react';
import {Plus,Pencil,ArrowRight,ShieldCheck,TrendingDown,Wallet,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {type State,type Loan,forecast,dayLabel} from '@/lib/money';
import {payoff,orderLoans} from '@/lib/debt';
export function LoanPanel({state:s,save,busy}:{state:State;save:(s:State)=>Promise<boolean>;busy:boolean}){
 const loans=s.loans??[],[editing,setEditing]=useState<Loan|null|undefined>(undefined),[deleting,setDeleting]=useState<Loan|null>(null),[extra,setExtra]=useState(String(s.debtExtra??0)),[localError,setLocalError]=useState('');
 const money=(n:number)=>new Intl.NumberFormat('en',{style:'currency',currency:s.currency,maximumFractionDigits:2,minimumFractionDigits:0}).format(n);
 const extraNumber=Number(extra.replace(/,/g,'')),validExtra=extra.trim()!==''&&Number.isFinite(extraNumber)&&extraNumber>=0&&extraNumber<=1e12;
 const active=loans.filter(l=>l.balance>0),spending=s.accounts.filter(a=>a.kind==='spending'),debt=active.reduce((n,l)=>n+l.balance,0),minimum=active.reduce((n,l)=>n+l.payment,0);
 const result=useMemo(()=>({baseline:payoff(loans,0,'minimum'),avalanche:payoff(loans,validExtra?extraNumber:0,'avalanche'),snowball:payoff(loans,validExtra?extraNumber:0,'snowball')}),[s.loans,extra,validExtra]);
 const target=orderLoans(active,'avalanche')[0],short=active.filter(l=>l.payment<=Math.round(l.balance*l.apr/1200*100)/100);
 const cashForecast=forecast(s,30),lowCash=Math.min(...cashForecast.points.map(p=>p.cash));
 const duration=(m:number|null)=>m===null?'Beyond 50 years':m===0?'Paid off':m+' month'+(m===1?'':'s');
 const goalDate=(months:number|null)=>{if(months===null)return 'No payoff within the model limit';const d=new Date(s.asOf+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);return d.toLocaleDateString('en',{month:'short',year:'numeric',timeZone:'UTC'})};
 async function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();setLocalError('');const fd=new FormData(e.currentTarget),str=(n:string)=>String(fd.get(n)??'').trim(),num=(n:string)=>Math.round(Number(str(n).replace(/,/g,''))*100)/100;
  const item:Loan={id:editing?.id??crypto.randomUUID(),name:str('name'),balance:num('balance'),apr:num('apr'),payment:num('payment'),dueDay:num('dueDay'),accountId:str('accountId')};
  if(!spending.some(a=>a.id===item.accountId)){setLocalError('Choose a spending account.');return}
  const updated=editing?loans.map(l=>l.id===editing.id?item:l):[...loans,item];
  if(await save({...s,loans:updated}))setEditing(undefined);else setLocalError('The loan was not saved. Close this form to see the wallet error, or retry.');
 }
 const modalTitle=editing?'Edit loan':'Add a loan';
 return <section className="panel debt-panel"><div className="section-title"><div><p className="eyebrow">LESS DEBT. MORE POSSIBILITY.</p><h2>A clearer path to paid off</h2><p className="fine">Know what you owe, choose your focus, and see what an extra payment could change.</p></div><button className="primary" disabled={busy||!spending.length||loans.length>=50} onClick={()=>{setLocalError('');setEditing(null)}}><Plus size={17}/> Add loan</button></div>
 {!loans.length?<div className="empty loan-empty"><TrendingDown size={32}/><h3>Make a plan for what you owe.</h3><p>Add a loan’s balance, annual interest rate and monthly minimum to get a personalized payoff comparison.</p>{!spending.length&&<p>Add a spending account in Accounts first.</p>}<div className="debt-principles"><div><b>1. Cover every minimum</b><span>Keep up with required payments before paying extra.</span></div><div><b>2. Choose a focus</b><span>Higher interest first can reduce interest costs.</span></div><div><b>3. Keep the momentum</b><span>Move a paid-off loan’s payment to the next one.</span></div></div></div>:<>
 <div className="debt-totals"><div><span>Total remaining debt</span><strong>{money(debt)}</strong></div><div><span>Monthly minimums</span><strong>{money(minimum)}</strong></div><div><span>Loans still to clear</span><strong>{active.length}<small> of {loans.length}</small></strong></div></div>
 <div className="loan-list">{loans.map(l=><article className="loan-row" key={l.id}><span className="event-icon">{l.balance===0?<Check size={20}/>:<Wallet size={20}/>}</span><div className="loan-name"><strong>{l.name}</strong><small>{l.balance===0?'Paid off':l.apr+'% annual interest'} · Due day {l.dueDay}</small></div><div><strong>{money(l.balance)}</strong><small>{money(l.payment)} minimum / month</small></div><button disabled={busy} aria-label={'Edit '+l.name} onClick={()=>{setLocalError('');setEditing(l)}}><Pencil size={16}/></button></article>)}</div>
 <p className="fine">Loan minimums are included in your cash forecast automatically. Remove any matching manual expense to avoid counting it twice. Update remaining balances during payday review.</p>
 {active.length>0&&<>
 <div className="debt-advice"><ShieldCheck size={26}/><div><p className="eyebrow">YOUR NEXT BEST FOCUS</p><h3>{target?.apr===0?'All your active loans are interest-free.':'Start with '+target?.name+'.'}</h3><p>{target?.apr===0?'Choose the smallest balance for an early win, while covering all required payments.':target?.name+' has your highest annual rate at '+target?.apr+'%. Cover every loan’s minimum, then direct affordable extra payments here. When it clears, move that payment to the next highest rate.'}</p></div></div>
 {short.length>0&&<div className="error"><strong>A minimum payment may not reduce the balance.</strong><p>{short.map(l=>l.name).join(', ')}: the entered minimum is at or below estimated monthly interest. Check the rate and payment with your lender; this balance may stay flat or grow without additional payments.</p></div>}
 {lowCash<0&&<div className="error"><strong>Protect your cash before adding extra.</strong><p>Your current routine, including loan minimums, projects cash as low as {money(lowCash)} in the next 30 days. Review essential spending and payment arrangements first.</p></div>}
 <div className="planner"><div className="section-title"><div><h3>What if you paid a little more?</h3><p className="fine">Try a monthly amount above all minimums. This is a scenario, not a payment instruction.</p></div></div><div className="extra-input"><label>Extra per month ({s.currency})<input type="number" min="0" max="1000000000000" step=".01" value={extra} onChange={e=>setExtra(e.target.value)} aria-describedby="extra-help"/></label><button disabled={busy||!validExtra} onClick={()=>save({...s,debtExtra:Math.round(extraNumber*100)/100})}>Save scenario</button><p id="extra-help" className="fine">{validExtra?'Total planned monthly budget: '+money(minimum+extraNumber):'Enter a valid amount of zero or more.'}</p></div>
 {validExtra&&<div className="strategy-grid">{(['baseline','avalanche','snowball'] as const).map((key)=>{const r=result[key],base=result.baseline,savedInterest=base.interest!==null&&r.interest!==null?Math.max(0,base.interest-r.interest):null;return <article key={key} className={'strategy '+(key==='avalanche'?'recommended':'')}><span className="eyebrow">{key==='baseline'?'YOUR COMPARISON':key==='avalanche'?'FOCUS ON INTEREST':'FOCUS ON QUICK WINS'}</span><h4>{key==='baseline'?'Minimums only':key==='avalanche'?'Highest interest first':'Smallest balance first'}</h4><strong>{duration(r.months)}</strong><span className="payoff-date">{goalDate(r.months)}</span><dl><div><dt>Estimated interest</dt><dd>{r.interest===null?'Not paid off in model':money(r.interest)}</dd></div>{key!=='baseline'&&savedInterest!==null&&<div><dt>Interest avoided</dt><dd>{money(savedInterest)}</dd></div>}</dl><p>{key==='baseline'?'Pay each entered minimum; stop its payment when cleared.':key==='avalanche'?'Put extra toward the highest rate, rolling cleared payments into the next loan.':'Put extra toward the smallest balance, rolling cleared payments into the next loan.'}</p></article>})}</div>}
 <p className="fine">Both focused strategies keep the original monthly budget after a loan clears—even with zero extra. Minimums-only does not roll freed payments forward. Saved scenarios do not add extra payments to the cash forecast; add a one-time expense when you plan an actual extra payment.</p>
 </div>
 <div className="debt-principles"><div><b>Protect your essentials</b><span>Choose an extra amount after bills and a cash cushion. A projected balance is not a guarantee of affordability.</span></div><div><b>Check your loan terms</b><span>Ask about early-payment charges and how extra payments are applied to principal. Confirm variable or promotional rates.</span></div><div><b>Review every payday</b><span>Update remaining balances from your statements. Recalculate when rates, payments or income change.</span></div></div>
 <details className="debt-assumptions"><summary>How these estimates work</summary><p>The model uses the annual interest rate divided by 12, adds interest monthly, then applies payments. Rates and entered minimums stay fixed, with no new borrowing, fees, missed payments or prepayment penalties. All loans are treated as monthly reducing-balance loans. Real daily interest, flat-rate loans and lender schedules can differ. Payoff dates are approximate months counted from {dayLabel(s.asOf)}. Cash forecasts schedule the minimum on the selected due day, using the month’s last day when needed, and stop at the estimated balance. A full month of interest is assumed even for the first partial month. Estimates stop at 600 months; “beyond 50 years” does not imply eventual payoff.</p></details>
 </>}
 {active.length===0&&<div className="debt-advice"><Check/><div><h3>You’ve cleared your recorded loans.</h3><p>Consider directing the freed monthly payment toward a savings goal on your vision board.</p></div></div>}
 </>}
 <p className="fine source">Learn about these approaches: <a href="https://www.consumerfinance.gov/archive/blog/how-reduce-your-debt/" target="_blank" rel="noreferrer">CFPB’s debt repayment guide <ArrowRight size={12}/></a></p>
 <Dialog open={editing!==undefined} onOpenChange={v=>{if(!v&&!busy)setEditing(undefined)}}><DialogContent className="editor"><DialogTitle>{modalTitle}</DialogTitle><DialogDescription>Use your latest statement. Enter the annual interest rate, not a monthly or flat fee rate.</DialogDescription><form onSubmit={submit} key={editing?.id??'new'}><label>Loan name<input name="name" required maxLength={100} defaultValue={editing?.name} placeholder="e.g. Credit card or personal loan"/></label><div className="form-grid"><label>Balance as of {dayLabel(s.asOf)}<MoneyInput name="balance" required type="number" min="0" max="1000000000000" step=".01" defaultValue={editing?.balance}/></label><label>Annual interest rate (%)<input name="apr" required type="number" min="0" max="100" step=".01" defaultValue={editing?.apr}/></label></div><div className="form-grid"><label>Monthly minimum ({s.currency})<MoneyInput name="payment" required type="number" min=".01" max="1000000000000" step=".01" defaultValue={editing?.payment}/></label><label>Payment due day (1–31)<input name="dueDay" required type="number" min="1" max="31" step="1" defaultValue={editing?.dueDay??15}/></label></div><label>Pay from<Select name="accountId" defaultValue={editing?.accountId??spending[0]?.id}><SelectTrigger className="pick"><SelectValue>{(v:any)=>spending.find(a=>a.id===v)?.name??'Choose an account'}</SelectValue></SelectTrigger><SelectContent>{spending.map(a=><SelectItem value={a.id} key={a.id}>{a.name}</SelectItem>)}</SelectContent></Select></label><p className="fine">This adds the minimum payment to your forecast. Do not also keep it as a separate recurring expense.</p>{localError&&<p className="error" role="alert">{localError}</p>}<div className="form-actions">{editing&&<button className="delete" type="button" disabled={busy} onClick={()=>setDeleting(editing)}>Delete</button>}<button type="button" disabled={busy} onClick={()=>setEditing(undefined)}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy?'Saving…':'Save loan'}</button></div></form></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v)setDeleting(null)}}><AlertDialogContent><AlertDialogTitle>Remove this loan?</AlertDialogTitle><AlertDialogDescription>It will leave your payoff plan and its minimum will no longer appear in the cash forecast. This does not pay off the loan.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep loan</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(await save({...s,loans:loans.filter(l=>l.id!==deleting?.id)})){setEditing(undefined)}setDeleting(null)}}>Remove loan</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>
}
